AWSTemplateFormatVersion: 2010-09-09
Description: AWS Cognito For G42
Parameters:
  G42PoolName:
    Type: String
    Default: G42Pool
  G42PoolClientName:
    Type: String
    Default: G42PoolClient
  G42PoolDomainName:
    Type: String
    Default: grou42-dal-cog
  G42SecretsID:
    Type: String
    Default: g42cogsecrets
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub ${G42PoolName}
      AutoVerifiedAttributes:
        - email
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      MfaConfiguration: OFF
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: "COGNITO_DEFAULT"
      VerificationMessageTemplate:
        DefaultEmailOption: "CONFIRM_WITH_LINK"
      EmailVerificationSubject: "Your verification link for registering on Dal Extracters is"
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: True
          RequireNumbers: True
          RequireSymbols: True
          RequireUppercase: True
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
      UsernameAttributes: [email]
      UsernameConfiguration:
        CaseSensitive: False
      UserPoolAddOns:
        AdvancedSecurityMode: "OFF"
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${G42PoolClientName}
      GenerateSecret: false
      PreventUserExistenceErrors: "ENABLED"
      UserPoolId: !Ref UserPool
  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub ${G42PoolDomainName}
      UserPoolId: !Ref UserPool
  SecretsManager:
    Type: "AWS::SecretsManager::Secret"
    DependsOn:
      - UserPool
      - UserPoolClient
    Properties:
      Name: !Sub ${G42SecretsID}
      SecretString:
        "Fn::Join":
          - ""
          - - '{"USER_POOL_ID":"'
            - Ref: UserPool
            - '","USER_POOL_CLIENT_ID":"'
            - Ref: UserPoolClient
            - '"}'
