Parameters:
  SecurityGroupDescription:
    Description: Security Group for Group42 Instance
    Type: String
  KeyName:
    Description: Key Pair for EC2
    Type: 'AWS::EC2::KeyPair::KeyName'

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0022f774911c1d690 
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref EC2SecurityGroup
      KeyName: !Ref KeyName
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
           sudo yum update -y
          sudo yum install git -y
          mkdir /home/ec2-user/cloud
          cd /home/ec2-user/cloud
          git clone https://callmehetch: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@github.com/callmehetch/group42-dal-client.git
          cd /home/ec2-user/cloud/group42-dal-client
          yum install -y gcc-c++ make
          yum install curl -y
          curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
          sudo yum install -y nodejs
          sudo yum install npm
          sudo npm i
          screen
          sudo npm start --host=0.0.0.0 --port=80

      Tags : [
            {"Key" : "Name", "Value" : "group42-dal-ec2-cf-a"}]

  EC2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: ami-0022f774911c1d690 
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref EC2SecurityGroup
      KeyName: !Ref KeyName
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update -y
          sudo yum install git -y
          mkdir /home/ec2-user/cloud
          cd /home/ec2-user/cloud
          git clone https://callmehetch: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@github.com/callmehetch/group42-dal-client.git
          cd /home/ec2-user/cloud/group42-dal-client
          yum install -y gcc-c++ make
          yum install curl -y
          curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
          sudo yum install -y nodejs
          sudo yum install npm
          sudo npm i
          screen
          sudo npm start --host=0.0.0.0 --port=80


      Tags : [
            {"Key" : "Name", "Value" : "group42-dal-ec2-cf-b"}]
          
  # security group
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ELB Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        SourceSecurityGroupId: 
          Fn::GetAtt:
          - ELBSecurityGroup
          - GroupId
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 5000
        ToPort: 5000
        CidrIp: 0.0.0.0/0
      Tags : [
            {"Key" : "Name", "Value" : "group42-dal-sg-cf"}]

  # Load Balancer for EC2
  LoadBalancerforEC2:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones: [us-east-1a, us-east-1b]
      Instances:
      - !Ref EC2Instance1
      - !Ref EC2Instance2
      Listeners:
      - LoadBalancerPort: '80'
        InstancePort: '80'
        Protocol: HTTP
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      SecurityGroups:
        - !GetAtt ELBSecurityGroup.GroupId